"""user_tier

Revision ID: 001688113254
Revises: 76376918368f
Create Date: 2026-01-16 02:43:49.738205

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# import sqlmodel import from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001688113254"
down_revision: str | Sequence[str] | None = "76376918368f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tier", sa.String(), server_default="free", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tier")
    # ### end Alembic commands ###
