"""increase short_code length

Revision ID: fdb143b1fb39
Revises: 5201e145432f
Create Date: 2026-01-16 17:14:35.307682

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdb143b1fb39"
down_revision: str | Sequence[str] | None = "5201e145432f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shorturls",
        "short_code",
        existing_type=sa.VARCHAR(length=7),
        type_=sqlmodel.sql.sqltypes.AutoString(length=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shorturls",
        "short_code",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=11),
        type_=sa.VARCHAR(length=7),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
